# -*- coding: utf-8 -*-
"""train_model.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1z7Ig1opqglbHy9_OMoPH8vUYbA_Ky_li
"""

import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler

from imblearn.over_sampling import SMOTE

import joblib

df = pd.read_csv('predictive analytics.csv')

le = LabelEncoder()

df['Type'] = le.fit_transform(df['Type'])

# Create temperature difference feature

df['Temp Difference'] = (
    df['Process temperature [K]']
    - df['Air temperature [K]']
)

# Create power-related feature

df['Power'] = (
    df['Torque [Nm]']
    * df['Rotational speed [rpm]']
)

X =df[[
 'Type',
 'Air temperature [K]',
 'Process temperature [K]',
 'Rotational speed [rpm]',
 'Torque [Nm]',
 'Tool wear [min]',
 'Temp Difference',
        'Power'
]]

y =df['Machine failure']

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)

X_test = scaler.transform(X_test)

# 4. Initialize and Train the Logistic Regression Model
rf_model = RandomForestClassifier(n_estimators=200,
    max_depth=10,
    min_samples_split=5,
    min_samples_leaf=2,
    class_weight='balanced',
    random_state=42)
rf_model.fit(X_train, y_train)

y_pred = rf_model.predict(X_test)

print(f"Random Forest Accuracy: {accuracy_score(y_test, y_pred):.2f}")
print("\nClassification Report:")
print(classification_report(y_test, y_pred))

cm = confusion_matrix(y_test, y_pred)
print("Raw Confusion Matrix:")
print(cm)

# Save trained model
joblib.dump(rf_model, 'machine_failure_model.pkl')

# Save scaler
joblib.dump(scaler, 'scaler.pkl')

print("Model and scaler saved successfully.")